### ISSUE TITLE
comonad-5.0.1 fails to build with GHC 9.0

### ISSUE THREAD

**Issue by Bodigrim** [ekmett/comonad#61]
```
Building library for comonad-5.0.1..
[ 1 of 15] Compiling Control.Comonad

src/Control/Comonad.hs:198:13: error:
    Suffix occurrence of @. For an as-pattern, remove the leading whitespace.
    |
198 |   extend f w@ ~(_ :| aas) = f w :| case aas of
    |
```

Could you please put a revision?
(I did not check other versions)

Upd.: Same for `comonad-5.0.4` and `comonad-5.0.5`.

**Comment by RyanGlScott** [comment]
Thanks for the heads-up. I've applied `base < 4.15` revisions for all versions of `comonad` that contain the `w@ ~(_ :| aas)` code, including versions `5.0.1`, `5.0.4`, and `5.0.5`.
